//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpvData
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvCampaignReportItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdvCampaignReportItem()
        {
            this.AdvCampaignReportItemMaterials = new HashSet<AdvCampaignReportItemMaterial>();
        }
    
        public System.Guid AdvCampaignReportItemGUID { get; set; }
        public System.Guid ReportGUID { get; set; }
        public string AdvCampaignReportItemOwner { get; set; }
        public int AdvCampaignID { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedWhen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdvCampaignReportItemMaterial> AdvCampaignReportItemMaterials { get; set; }
        public virtual AdvCampaign AdvCampaign { get; set; }
        public virtual Report Report { get; set; }
        public virtual User User { get; set; }
    }
}
