//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpvData
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvCampaignReportItemMaterial
    {
        public System.Guid AdvCampaignReportItemGUID { get; set; }
        public int AdvCampaignMaterialID { get; set; }
        public System.Guid ReportGUID { get; set; }
        public string AdvCampaignReportItemMaterialOwner { get; set; }
        public decimal AdvCampaignReportItemMaterialQty { get; set; }
        public string AdvCampaignReportItemMaterialComment { get; set; }
    
        public virtual AdvCampaignMaterial AdvCampaignMaterial { get; set; }
        public virtual AdvCampaignReportItem AdvCampaignReportItem { get; set; }
        public virtual User User { get; set; }
    }
}
