//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpvData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertising
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Advertising()
        {
            this.AdvertisingReportItems = new HashSet<AdvertisingReportItem>();
        }
    
        public int AdvertisingID { get; set; }
        public string AdvertisingName { get; set; }
        public string AdvertisingShortName { get; set; }
        public System.DateTime AdvertisingValidThrough { get; set; }
        public System.DateTime AdvertisingActiveThrough { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedWhen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdvertisingReportItem> AdvertisingReportItems { get; set; }
    }
}
