//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpvData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categories4
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Categories4()
        {
            this.Skus = new HashSet<Sku>();
        }
    
        public int Category4ID { get; set; }
        public int Category3ID { get; set; }
        public string Category4Name { get; set; }
        public int SkuCount { get; set; }
        public bool Category4Active { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedWhen { get; set; }
        public string Category4NameEng { get; set; }
        public bool Category4OutputToMerchXls { get; set; }
    
        public virtual Categories3 Categories3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sku> Skus { get; set; }
    }
}
