//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpvData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category1UserSubroleMappings
    {
        public int Category1ID { get; set; }
        public int UserSubroleID { get; set; }
    
        public virtual Categories1 Categories1 { get; set; }
    }
}
