//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpvData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categories2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Categories2()
        {
            this.Categories3 = new HashSet<Categories3>();
        }
    
        public int Category2ID { get; set; }
        public int Category1ID { get; set; }
        public string Category2Name { get; set; }
        public int Category3Count { get; set; }
        public bool Category2Active { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedWhen { get; set; }
        public string Category2NameEng { get; set; }
        public bool Category2OutputToMerchXls { get; set; }
        public bool Category2NoSalesQty { get; set; }
    
        public virtual Categories1 Categories1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Categories3> Categories3 { get; set; }
    }
}
