//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpvData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientOffice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientOffice()
        {
            this.ListingClientOfficeMappings = new HashSet<ListingClientOfficeMapping>();
            this.RouteClientOffices = new HashSet<RouteClientOffice>();
            this.RouteClientOfficesDistincts = new HashSet<RouteClientOfficesDistinct>();
            this.Users = new HashSet<User>();
            this.Visits = new HashSet<Visit>();
        }
    
        public int ClientOfficeID { get; set; }
        public int ClientOfficeClassificationID { get; set; }
        public int ClientID { get; set; }
        public int CityID { get; set; }
        public string SupervisorUserLoginName { get; set; }
        public string MerchSupervisorUserLoginName1 { get; set; }
        public string MerchSupervisorUserLoginName2 { get; set; }
        public string MerchSupervisorUserLoginName3 { get; set; }
        public string MerchSupervisorUserLoginName4 { get; set; }
        public string MerchSupervisorUserLoginName5 { get; set; }
        public string ClientOfficeName { get; set; }
        public string ClientOfficeShortName { get; set; }
        public string ClientOfficeAddress { get; set; }
        public bool ClientOfficeActive { get; set; }
        public string ClientOfficeComments { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedWhen { get; set; }
        public string ClientOfficeClassificationExternal { get; set; }
        public string SupervisorUserLoginName2 { get; set; }
        public string SupervisorUserLoginName3 { get; set; }
        public string SupervisorUserLoginName4 { get; set; }
        public string SupervisorUserLoginName5 { get; set; }
        public Nullable<decimal> ClientOfficeArea { get; set; }
        public string AnalystUserLoginName1 { get; set; }
        public string AnalystUserLoginName2 { get; set; }
        public string AnalystUserLoginName3 { get; set; }
        public string AnalystUserLoginName4 { get; set; }
        public string AnalystUserLoginName5 { get; set; }
        public string ClientOfficeNumberExternal { get; set; }
        public string ClientOfficeFocusSubcategory { get; set; }
        public bool ClientOfficeShowInPlans { get; set; }
        public Nullable<int> ClientOfficeShelfVolume { get; set; }
        public Nullable<int> ClientOfficeTrafficID { get; set; }
        public Nullable<int> ClientOfficeTypeID { get; set; }
        public Nullable<int> ClientOfficeSKUQuantity { get; set; }
        public Nullable<int> ClientOfficeLGConsultants { get; set; }
        public Nullable<int> ClientOfficeSamsungConsultants { get; set; }
        public Nullable<int> ClientOfficeToshibaConsultants { get; set; }
        public Nullable<int> ClientOfficeSonyConsultants { get; set; }
        public Nullable<int> ClientOfficePanasonicConsultants { get; set; }
        public Nullable<decimal> ClientOfficeTotalSelloutCurrent { get; set; }
        public Nullable<decimal> ClientOfficeTotalSelloutPrevious { get; set; }
        public Nullable<decimal> ClientOfficePhilipsSelloutCurrent { get; set; }
        public Nullable<decimal> ClientOfficePhilipsSelloutPrevious { get; set; }
        public string ClientOfficeClassificationRR { get; set; }
    
        public virtual City City { get; set; }
        public virtual Client Client { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual User User3 { get; set; }
        public virtual User User4 { get; set; }
        public virtual User User5 { get; set; }
        public virtual User User6 { get; set; }
        public virtual User User7 { get; set; }
        public virtual User User8 { get; set; }
        public virtual User User9 { get; set; }
        public virtual User User10 { get; set; }
        public virtual User User11 { get; set; }
        public virtual User User12 { get; set; }
        public virtual User User13 { get; set; }
        public virtual User User14 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListingClientOfficeMapping> ListingClientOfficeMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RouteClientOffice> RouteClientOffices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RouteClientOfficesDistinct> RouteClientOfficesDistincts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Visit> Visits { get; set; }
    }
}
