//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpvData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.ClientOffices = new HashSet<ClientOffice>();
        }
    
        public int ClientID { get; set; }
        public int ClientClassificationID { get; set; }
        public int VisitRuleID { get; set; }
        public string ClientName { get; set; }
        public int ClientOfficeCount { get; set; }
        public bool ClientActive { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedWhen { get; set; }
        public int CountryID { get; set; }
        public bool ClientUseMinSkuQty { get; set; }
        public Nullable<int> SortOrderInFilter { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientOffice> ClientOffices { get; set; }
        public virtual VisitRule VisitRule { get; set; }
    }
}
