//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpvData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetitorReport
    {
        public System.Guid ReportGUID { get; set; }
        public string CompetitorReportOwner { get; set; }
        public int CompetitorAdvertisingGeneration { get; set; }
    
        public virtual Report Report { get; set; }
        public virtual User User { get; set; }
    }
}
