//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpvData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetitorAdvertising
    {
        public int CompetitorAdvertisingGeneration { get; set; }
        public int CompetitorAdvertisingNum { get; set; }
        public string CompetitorAdvertisingName { get; set; }
        public int CompetitorAdvertisingOrderNum { get; set; }
    }
}
