//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpvData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MerchantReportItemsTempStore
    {
        public System.Guid MerchantReportItemTempStoreGUID { get; set; }
        public System.Guid ReportTempStoreGUID { get; set; }
        public System.Guid ReportGUID { get; set; }
        public int SkuID { get; set; }
        public decimal MerchantReportItemPrice { get; set; }
        public decimal MerchantReportItemQty { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedWhen { get; set; }
        public System.DateTime TempStoreCreatedWhen { get; set; }
        public Nullable<decimal> MerchantReportItemOnShelf { get; set; }
    
        public virtual Sku Sku { get; set; }
    }
}
