//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpvData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoReportItem
    {
        public System.Guid PhotoReportItemGUID { get; set; }
        public System.Guid ReportGUID { get; set; }
        public string PhotoReportItemOwner { get; set; }
        public string PhotoReportItemDescription { get; set; }
        public byte[] PhotoReportItemThumbnail { get; set; }
        public byte[] PhotoReportItemPhoto { get; set; }
        public Nullable<int> PhotoReportItemTagID1 { get; set; }
        public Nullable<int> PhotoReportItemTagID2 { get; set; }
        public Nullable<int> PhotoReportItemTagID3 { get; set; }
        public Nullable<int> PhotoReportItemTagID4 { get; set; }
        public Nullable<int> PhotoReportItemTagID5 { get; set; }
        public Nullable<int> PhotoReportItemTagID6 { get; set; }
        public Nullable<int> PhotoReportItemTagID7 { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedWhen { get; set; }
        public int PhotoReportItemWidth { get; set; }
        public int PhotoReportItemHeight { get; set; }
        public byte[] PhotoReportItemPhotoModified { get; set; }
        public int PhotoReportItemAngle { get; set; }
        public byte[] PhotoReportItemPreview { get; set; }
        public Nullable<System.DateTime> PhotoReportItemExifTimeStamp { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public Nullable<int> PhotoReportItemTagID8 { get; set; }
        public Nullable<int> PhotoReportItemTagID9 { get; set; }
        public Nullable<bool> IsCategory1Selected { get; set; }
        public Nullable<bool> IsCategory2Selected { get; set; }
        public Nullable<bool> IsCategory3Selected { get; set; }
        public Nullable<bool> IsCategory4Selected { get; set; }
    
        public virtual PhotoReportTag PhotoReportTag { get; set; }
        public virtual PhotoReportTag PhotoReportTag1 { get; set; }
        public virtual PhotoReportTag PhotoReportTag2 { get; set; }
        public virtual PhotoReportTag PhotoReportTag3 { get; set; }
        public virtual PhotoReportTag PhotoReportTag4 { get; set; }
        public virtual PhotoReportTag PhotoReportTag5 { get; set; }
        public virtual PhotoReportTag PhotoReportTag6 { get; set; }
        public virtual PhotoReportTag PhotoReportTag7 { get; set; }
        public virtual PhotoReportTag PhotoReportTag8 { get; set; }
        public virtual Report Report { get; set; }
        public virtual User User { get; set; }
    }
}
