//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpvData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PortionReportItemsTempStore
    {
        public System.Guid PortionReportItemTempStoreGUID { get; set; }
        public System.Guid ReportTempStoreGUID { get; set; }
        public System.Guid ReportGUID { get; set; }
        public int Category3ID { get; set; }
        public int BrandID { get; set; }
        public decimal PortionReportItemQty { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedWhen { get; set; }
        public System.DateTime TempStoreCreatedWhen { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Categories3 Categories3 { get; set; }
    }
}
