//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpvData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Route()
        {
            this.RouteClientOffices = new HashSet<RouteClientOffice>();
            this.RouteClientOfficesDistincts = new HashSet<RouteClientOfficesDistinct>();
        }
    
        public int RouteID { get; set; }
        public string UserLoginName { get; set; }
        public System.DateTime RouteDateFrom { get; set; }
        public System.DateTime RouteDateTo { get; set; }
        public int RouteNumWeeks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RouteClientOffice> RouteClientOffices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RouteClientOfficesDistinct> RouteClientOfficesDistincts { get; set; }
        public virtual User User { get; set; }
    }
}
