//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpvData
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouteClientOffice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RouteClientOffice()
        {
            this.RouteClientOfficeExceptions = new HashSet<RouteClientOfficeException>();
        }
    
        public int RouteID { get; set; }
        public int RouteClientOfficeWeekNumber { get; set; }
        public int RouteClientOfficeDayOfWeek { get; set; }
        public int ClientOfficeID { get; set; }
        public string UserLoginName { get; set; }
    
        public virtual ClientOffice ClientOffice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RouteClientOfficeException> RouteClientOfficeExceptions { get; set; }
        public virtual Route Route { get; set; }
        public virtual User User { get; set; }
    }
}
