//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpvData
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouteClientOfficeException
    {
        public int RouteID { get; set; }
        public int RouteClientOfficeWeekNumber { get; set; }
        public int RouteClientOfficeDayOfWeek { get; set; }
        public int ClientOfficeID { get; set; }
        public System.DateTime WeekdayDate { get; set; }
        public string UserLoginName { get; set; }
    
        public virtual RouteClientOffice RouteClientOffice { get; set; }
        public virtual User User { get; set; }
    }
}
