//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpvData
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitRulesType2
    {
        public int VisitRuleID { get; set; }
        public System.DateTime VisitRuleDate { get; set; }
        public System.DateTime VisitRuleFinishDate { get; set; }
    
        public virtual VisitRule VisitRule { get; set; }
    }
}
